CREATE TABLE IF NOT EXISTS c_wallet (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL UNIQUE,
  BALANCE DECIMAL(15,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS c_transactions (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  AMOUNT DECIMAL(15,2) NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);